{% set name = "torchmetrics" %}
{% set version = "0.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Update an url to https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # when the package will be available on PyPI.
  url: https://github.com/Lightning-AI/metrics/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fb58c830b67902acfd0fc5ddee268a64bdc476c41fb571347c6134c261f1723d

build:
  number: 1
  # pytorch hasn't python 3.11 support on ppc64le
  skip: True  # [py<37 or ((linux and ppc64le) and py>311))]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - numpy
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.17.2
    - packaging  # hotfix for utils, can be dropped with lit-utils >=0.5
    - pytorch >=1.8.1,<2.0.0
    - typing-extensions  # [py<39]

test:
  imports:
    - torchmetrics
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/torchmetrics/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Collection of PyTorch native metrics for easy evaluating machine learning models
  description: |
    Torchmetrics is a metrics API created for easy metric development and usage in both PyTorch and
    [PyTorch Lightning](https://pytorch-lightning.readthedocs.io/en/stable/). It was originally a part of
    Pytorch Lightning, but got split off so users could take advantage of the large collection of metrics
    implemented without having to install Pytorch Lightning (even though we would love for you to try it out).
    We currently have around 25+ metrics implemented and we continuously is adding more metrics, both within
    already covered domains (classification, regression ect.) but also new domains (object detection ect.).
    We make sure that all our metrics are rigorously tested such that you can trust them.
  doc_url: https://torchmetrics.readthedocs.io/
  dev_url: https://github.com/PyTorchLightning/metrics

extra:
  recipe-maintainers:
    - Borda
    - williamFalcon
  skip-lints:
    - python_build_tool_in_run
